sonar.projectKey=KayzKiet1_Journal-Trend-Analyzer
sonar.organization=kayzkiet1
sonar.projectName=Journal-Trend-Analyzer
sonar.projectVersion=1.0

sonar.sources=lib
sonar.tests=test
sonar.test.inclusions=test/**/*_test.dart

sonar.sourceEncoding=UTF-8

sonar.exclusions=build/**,.dart_tool/**,.idea/**,android/**,ios/**,linux/**,macos/**,windows/**,patrol_test/**,**/*.g.dart,**/*.freezed.dart
sonar.coverage.exclusions=test/**,patrol_test/**,**/*_test.dart,lib/main.dart,lib/screens/**,lib/widgets/**,lib/utils/app_*.dart,lib/utils/api_constants.dart,lib/firebase/**,lib/services/openalex_service.dart,lib/services/dashboard_report_service.dart,lib/viewmodels/compare_journals_view_model.dart,lib/viewmodels/home_view_model.dart,lib/viewmodels/journal_detail_view_model.dart,lib/viewmodels/keyword_detail_view_model.dart,lib/viewmodels/keywords_view_model.dart,lib/viewmodels/notification_view_model.dart,lib/viewmodels/profile_view_model.dart,lib/viewmodels/publication_detail_view_model.dart,lib/viewmodels/publication_view_model.dart,lib/viewmodels/user_view_model.dart,lib/models/app_notification_model.dart,lib/models/keyword_dashboard_model.dart
sonar.cpd.exclusions=lib/screens/**,lib/widgets/**,lib/firebase/**,lib/services/dashboard_report_service.dart,patrol_test/**
sonar.dart.lcov.reportPaths=coverage/lcov.info
