sonar.projectKey=KayzKiet1_Journal-Trend-Analyzer
sonar.organization=kayzkiet1
sonar.projectName=Journal-Trend-Analyzer
sonar.projectVersion=1.0

sonar.sources=lib
sonar.tests=test
sonar.test.inclusions=test/**/*_test.dart

sonar.sourceEncoding=UTF-8

sonar.exclusions=build/**,.dart_tool/**,.idea/**,android/**,ios/**,linux/**,macos/**,windows/**,web/**,**/*.g.dart,**/*.freezed.dart
sonar.coverage.exclusions=test/**,**/*_test.dart,lib/main.dart,lib/screens/**,lib/widgets/**,lib/utils/app_*.dart,lib/utils/api_constants.dart,lib/firebase/**,lib/services/openalex_service.dart,lib/services/dashboard_report_service.dart,lib/controllers/notification_controller.dart,lib/controllers/publication_controller.dart,lib/controllers/user_controller.dart,lib/models/app_notification_model.dart
sonar.dart.lcov.reportPaths=coverage/lcov.info
