sonar.projectKey=journal_trend_analyzer
sonar.projectName=Journal Trend Analyzer
sonar.projectVersion=1.0

sonar.sources=lib
sonar.tests=test
sonar.test.inclusions=test/**/*_test.dart

sonar.sourceEncoding=UTF-8

sonar.exclusions=build/**,.dart_tool/**,.idea/**,android/**,ios/**,linux/**,macos/**,windows/**,web/**,**/*.g.dart,**/*.freezed.dart
sonar.coverage.exclusions=test/**,**/*_test.dart
sonar.dart.lcov.reportPaths=coverage/lcov.info
